### ISSUE TITLE
Can't decode recorded .wav file 

### ISSUE THREAD

**Issue by VolodymyrTymets** [mohayonao/wav-decoder#11]
I did record .wav via [mic](https://www.npmjs.com/package/mic). Here my code.
```
var micInstance = mic({
    rate: '16000',
    channels: '1',
    debug: true,
    exitOnSilence: 6,
    device: 'plughw:0',
    fileType: 'wav',
});

var micInputStream = micInstance.getAudioStream();

var outputFileStream = fs.WriteStream('output.wav');

micInputStream.pipe(outputFileStream);

micInstance.start();
```

When i try to decode  `output.wav` i have exception: 
```
 RangeError: Offset is outside the bounds of the DataView
    at DataView.getInt16 (<anonymous>)
```

**Comment by mohayonao** [comment]
I tried your code with `mic` (not [2.1.1](https://github.com/ashishbajaj99/mic/tree/49648ca31f01c0e063728de2aef0b6a5a1340418), I'm using [the latest version](https://github.com/ashishbajaj99/mic/tree/ede43554f04a34dbfa746d93d3c26d0cf1d11451) on GitHub).

In my Mac environment (use `rec` command),
`mic` create a file that has indeterminate data chunk size (2GB).
That attempts to read to outside the bounds of the DataView, and raise RangeError.

I fixed this issue at v1.1.1, if data chunk size is too big length then take appropriate length.

**Comment by VolodymyrTymets** [comment]
Now its work. thanks! 

One more question.

In [mic](https://www.npmjs.com/package/mic) are method `on('data', ...)` to get recorded stream on fly.

```
micInputStream.on('data', function(data) {
    console.log("Recieved Input Stream: " + data.length);
    WavDecoder.decode(data)
});
```
Is possible to decode this striam to make calculation on fly, or it's not possible ?

**Comment by mohayonao** [comment]
This decoder is not support stream.
I wanted a lightweight wav decoder that works in the browser and Node.js both, so I made this.

Please try [node-wav](https://github.com/tootallnate/node-wav) or `mic({ fileType: "f32" })`.

**Comment by VolodymyrTymets** [comment]
Thank for help.
